sudo: false

language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

install:
  - composer require --dev php-coveralls/php-coveralls

script:
  - composer update
  - composer fix-style
  - composer check-style
  - composer test

after_success:
  - vendor/bin/php-coveralls -v
